name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Install dependencies
      - run: npm install --dev

      # Pass secrets
      - name: "Write .env"
        run: echo "FRED_API_KEY=$FRED_API_KEY" > .env && echo "BLS_API_KEY=$BLS_API_KEY" >> .env
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          BLS_API_KEY: ${{ secrets.BLS_API_KEY }}

      # Run tests
      - name: "Run npm test"
        run: npm test
